# yaml file for shanghai tech
# ShanghaiTechFeature.yaml
# in SRF it is unmerged

TRAIN:
  ENABLE: True
  DATASET: SH_SRF
  BATCH_SIZE: 1
  CHECKPOINT_PERIOD: 25

TECH:
#  INPUT_CHANNEL_NUM: 3
  PATH_TO_DATA_DIR: E:/datasets/shanghaitech_C3D_Feature/split_npy
  TEST_MODE: test_merged_l2norm
  #test_merged_l2norm test_unmerged_l2norm
#  PIXEL_MAT_FOLDER: F:/shanghaitech/testing/test_pixel_mask
#  FRAME_MAT_FOLDER: F:/shanghaitech/testing/test_frame_mask

SOLVER:
  BASE_LR: 0.00005
  LR_POLICY: keep
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.00005
  OPTIMIZING_METHOD: adam
  LOSS_FUNC: SRF_LOSS_COMBINE
#  STEP_EPOCHS: [10,30]
  MAX_ITERATION: 10000
  STEP_ITERATIONS: [4000,8000]

MODEL:
  MODEL_NAME: SRF_FC #FC_3_layer

TEST:
  ENABLE: True
  DATASET: SH_SRF
  BATCH_SIZE: 1
  SAVE_NPY_PATH: E:/letter-experiment-SRF_version2/SH/dynamic_margin_warmup
#E:/letter-experiment/shanghaitech/origin/pred_score_merged

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

MEMORY_BANK:
  BANK_SIZE: 175
#TENSORBOARD:
#  PATH: F:/shanghaitech_past_meet_future/board

NUM_GPUS: 1
TRAIN_LOGFILE_NAME: tech_train.log
TEST_LOGFILE_NAME: tech_test.log
AUC_LOGFILE_NAME: tech_AUC.log
OUTPUT_DIR: E:/letter-experiment-SRF_version2/SH/dynamic_margin_warmup

